import { Container } from '@mui/material'
import Head from 'next/head'
import { initializeApollo, addApolloState } from '../apolloClient'

import List from '../components/List'

import { ALL_CHARACTERS } from '../queries/ListQuery'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <List />
      </Container>
    </>
  )
}

export async function getStaticProps() {
  const apolloclient = initializeApollo()

  await apolloclient.query({
    query: ALL_CHARACTERS,
    variables: {
      page: 1
    }
  })

  return addApolloState(apolloclient, {
    props: {},
    revalidate: 1,
  })
}

export default Home
